### ISSUE TITLE
Inconsistent service name manipulation between broker and register-broker errand

### ISSUE THREAD

**Issue by mboldt** [cf-platform-eng/kibosh#11]
In the broker configuration, kibosh replaces `_` with `-` here: https://github.com/cf-platform-eng/kibosh/blob/967f29a762541101c282c7b1b0e5236e8995b097/config/config.go#L87

In the broker-register errand, the service name is used without this replacement here: https://github.com/cf-platform-eng/kibosh/blob/967f29a762541101c282c7b1b0e5236e8995b097/bosh-release/jobs/register-broker/templates/errand.sh.erb#L57

This causes the errand to fail when the service name contains `_`.

Perhaps simplest would be validate the service name against a regex, and blow up if it contains `_`s (or other special characters). Alternatively, manipulate the service name the register-broker errand as well, but that seems like unnecessary complexity...solve things in data when possible, not code.

**Comment by keshto** [comment]
https://github.com/cf-platform-eng/tile-generator/commit/a1817cd9029ef021ff1881a5f750adf0e5ba38b2
This should fix it if not please let me know

**Comment by mboldt** [comment]
That fixes it when using tile-generator, but outside of tile-generator if the `serivice_name` contains a `_` it is still an issue.

We had a chat that yielded two possible solutions:

1. Kibosh broker rejects `_` in `service_name`:
  Pros: keeps code simple; e.g., a single regex check at startup.
  Cons: defers detection until `bosh deploy` time. Would require rejection or sanitization in tile-generator as well (otherwise tile developers would have to wait a full tile build/upload/configure/deploy cycle to detect a silly naming format issue).

2. Kibosh broker *and* register-broker errand sanitize `service_name`:
  Pros: users (including tile-generator) don't have to worry about naming format/restrictions.
  Cons: More complex code; need for synchronization between broker job and register-broker errand.

**Comment by cholick** [comment]
Given the pain we've seen around tile-gen and auto-swapping `-` / `_`, my vote is to fail fast and restrict name (1). This also makes debugging easier, as a final consumer wouldn't have to understand we're doing transformations.

**Comment by mboldt** [comment]
That works for me. @keshto how about instead of converting `_` to `-` in tile-generator to avoid the pain, we just have the same restriction on the name of packages with `type: kibosh`?

**Comment by keshto** [comment]
Tile-gen has a restriction that it only allows `_`s because transforming is not deterministic in properties. My suggestion is to change the errand to do the transformation and be in sync with what the kibosh binary is doing. This would need to be documented so that consumers wouldn't get confused about it.

**Comment by mboldt** [comment]
Just for added context, `_`s are not allowed in the service name in the catalog endpoint of the OSBAPI spec. (I had previously assumed it was further downstream, in the k8s deployment, where this was an issue, but upon further inspection it looks like the service name is not used in that context.)

**Comment by mboldt** [comment]
After some out-of-band chat, it sounds like we're landing on the errand job doing the `_` to `-` conversion as well.

**Comment by cholick** [comment]
No longer relevant.
