### ISSUE TITLE
suggestion for service type: nodeport handling

### ISSUE THREAD

**Issue by nouseforaname** [cf-platform-eng/kibosh#19]
Hello,

I wan't to propose a feature where setting service to NodePort will return a a list of externalIPs populated with worker IPs and optionally one workerIp as clusterIP in Bind step. This way the services could be consumed externally even on cloud providers that do not offer type: LoadBalancer for service. 

I forked your Repo @ https://github.com/starkandwayne/kibosh and added a commit that has these changes. "It works" locally. I went with populating externalIPs field with workerIPs that was already present but empty. 

Best, 

Konstantin

**Comment by cholick** [comment]
The risk with this change is that if the cluster is ever scaled down, services could be bound to an IP that's no longer in the pool of workers

This is the reason we've required `LoadBalancer` so far, it limits things, but it also doesn't pose risk of breaking during cluster scale events or introduce windows of service downtime during worker node maintenance.

**Comment by cholick** [comment]
Though maybe this could be useful in a non-production environment?

**Comment by nouseforaname** [comment]
Yes you are right and I'm are aware of that issue. 
On the other Hand that is always the case by consuming NodePort with Kubernetes. But the alternative is complete lockout while looking into kibosh as a solution.

**Comment by cholick** [comment]
Cool. Did you want to PR that change in @nouseforaname? Code looks good, but would appreciate a unit test and running a go format before the PR (the default will do a `fmt`)

**Comment by nouseforaname** [comment]
K, will do so.

**Comment by nouseforaname** [comment]
https://github.com/starkandwayne/kibosh/commits/master

I added tests and hopefully fmt'ed all the files. Let me know if it's okay to PR

**Comment by cholick** [comment]
Code looks good! PR away.

We'll probably tweak the README.md a bit more after, to add a bit stronger warning around the potential drawbacks of using `NodePort` (or you could add those cautions if you'd rather)

**Comment by cholick** [comment]
Fixed by #20
