### ISSUE TITLE
Need support for workload using K8 Job

### ISSUE THREAD

**Issue by gmflau** [cf-platform-eng/kibosh#26]
Our pks tile's implementation has a K8 Job artifact.  Kibosh does not handle it properly.  As a result, the "create-service" status is stuck at "create in progress".  In K8 control plan, it shows my K8 Job completed as below:

pod/kibosh-2e96205e-12a9-4c51-8069-fe0d9ff94a57-dse-init-hz457   0/1       Completed   0          19h

I would suggest to inspect the kibosh code to see if the condition statement to verify readiness of a pod for a K8 job is correctly defined.  The code should verify if (READY == 1/1 & STATUS == Running) or (STATUS == Completed) for a Pod to determine create-service's status as "create succeeded".

**Comment by joeeltgroth** [comment]
Issues: 1) should be checking for "Succeeded" rather than "Completed" jobs, 2) Jobs may run for awhile and need to be certain we don't call the deployment succeeded even if the job pod is "Running"
