### ISSUE TITLE
Timeouts for service instance provisioning

### ISSUE THREAD

**Issue by aegershman** [cf-platform-eng/kibosh#30]
As an operator who makes helm chart mistakes, I have occasionally had service instances get stuck indefinitely in a "service instance creation in process" state with no way to stop or delete them. Is it possible to have the service broker timeout when service instance provisioning/deletion goes past a certain point?

Here's the workflow that causes it:

- Prepare a helm chart to be used with kibosh
- Upload it using `bazaar-cli`
- Try to provision a service instance of that chart
- Realize I made a mistake with the helm chart, improperly uploaded the persistent volume claim definition, or some other oversight on my part
- The service instance can't be provisioned properly because something is bonked up on the back-end

Which gives an operator two options: fix whatever is wrong with the kibosh definition so the instance provisions properly, or purge the service instance from `cf`, which leaves residual resources left out in the kibosh kubernetes cluster.

**Comment by cholick** [comment]
Unfortunately, the platform (Cloud Foundry) calling the broker is responsible for choosing the timeout. As a broker, we don't get to pick the value. It will eventually time out, but the value is 7 days:
* https://github.com/cloudfoundry/cloud_controller_ng/blob/master/config/cloud_controller.yml#L55

Which is configurable via BOSH
* https://github.com/cloudfoundry/capi-release/blob/master/jobs/cloud_controller_worker/spec#L467

We could do some time checks on our side, if we wanted to explicitly fail sooner, but I have reservations about adding an explicit override in our service when there's already a configurable platform default.

Any thoughts @beazer @jshah-pivotal @aaronmeza @jkjell @guidowb?

**Comment by cholick** [comment]
I've suggested a change to the OSBAPI spec that would gives us the handle we need to add a timeout.

https://github.com/openservicebrokerapi/servicebroker/pull/627

**Comment by aegershman** [comment]
Interesting, thank you. I hope the issue I brought up is valid & isn't leading you or anyone on a wild goose chase. To be perfectly honest I definitely don't understand all the potential implications of the OSBAPI change; I definitely trust your professional judgment on this.

Assuming a reasonable timeout could be configured && that timeout was hit, would that then trigger the kibosh broker to terminate/cleanup the resources it provisioned (but are in a failure state)?

**Comment by cholick** [comment]
In addition to the change to the spec (which should address it for the OSS Kibosh), we've have implemented a specific mitigating solution to this in the closed source product that is based on Kibosh.
