### ISSUE TITLE
Revise docs for Helm 3

### ISSUE THREAD

**Issue by mogul** [cf-platform-eng/kibosh#44]
[Helm 3 is dropping Tiller](https://github.com/helm/helm/releases/tag/v3.0.0-alpha.1), which should simplify setup. The docs should be updated to match.

**Comment by cholick** [comment]
We definitely plan to move to Helm 3 when it's GA (to remove the complexity of tiller). At this point, though, it's still Beta.

**Comment by kvaps** [comment]
Hi, what is current state of Helm 3 support?
