### ISSUE TITLE
Credhub is not configured in the Bosh release

### ISSUE THREAD

**Issue by ThilinaManamgoda** [cf-platform-eng/kibosh#61]
According to the Kibosh implementation,  the CredHub URL is configured through the environment variable "CH_CRED_HUB_URL". But I couldn't find this configuration in the Kibosh Bosh release. Am I missing something here?

**Comment by cholick** [comment]
We haven't put it in the OSS BOSH release yet; it is in the closed-source BOSH release that's built on Kibosh, though.
